### PR TITLE
Adding support for English date format.

### PR DESCRIPTION
**Pull request by Ectalite**

### CODE REVIEW

**Comment by Ectalite** [comment]
As you reverted my changes, please download my source and test my changes. They shouldn't impact the performances at all.

**Comment by Ectalite** [comment]
Ok I tried something else.
It should be way more smoother at start and should work with every formats...
Let's try that !

**Comment by mrusse** [comment]
Everything works on my end and it loads quick. So this fix also worked for date formats other than English? it looks like it just parses the date one way with "DateTime.TryParse". Either way the error handing is better than I had it before so thank you for the change.

**Comment by Ectalite** [comment]
I tested it with my datas and it worked 😂.
Such a simple modification.

**Pull request merged**
